FROM node:20-bullseye

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install the application dependencies
RUN npm install

# Create a non-root user
RUN useradd --create-home --shell /bin/bash app && chown -R app:app /app
USER app

# Expose Vite's development port
EXPOSE 5173

# Command to run development server with hot reload
CMD ["npm", "run", "dev"]
